services:
  - type: web
    name: backend-taskmanager
    env: python
    buildCommand: |
      python manage.py makemigrations
      python manage.py migrate --noinput
    startCommand: gunicorn tasks.wsgi:application
